---

- hosts: all
  become: true
  tasks:   

  - name: install apache2 and php package for Ubuntu
    apt: 
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes

  - name: Asegurar que el servicio Apache2 esté corriendo y habilitado
    ansible.builtin.service:
      name: apache2
      state: started
      enabled: yes



