---

- hosts: all
  become: true
  tasks:   

  - name: install apache2 and php package for Ubuntu
    apt: 
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes


