---

- hosts: gcp_server
  become: true
  vars:
    ansible_user: dfcarrera1979
    nginx_container_name: quasar-nginx
    nginx_volume_path: /home/{{ ansible_user }}/quasar-deploy
    nginx_config_path: /home/{{ ansible_user }}/nginx.conf

  tasks:

    - name: Actualizar el sistema
      apt:
        upgrade: dist
        update_cache: yes
      tags: always

    - name: Instalar Docker y Docker Compose
      apt:
        name:
          - docker.io
          - docker-compose
        state: present

    - name: Habilitar Docker al iniciar el sistema
      systemd:
        name: docker
        enabled: yes

    - name: Iniciar el servicio Docker
      systemd:
        name: docker
        state: started

    - name: Instalar UFW (Uncomplicated Firewall)
      apt:
        name: ufw
        state: present
        update_cache: yes

    - name: Permitir puerto HTTP (80)
      ufw:
        rule: allow
        port: "80"
        proto: tcp

    - name: Permitir puerto HTTPS (443)
      ufw:
        rule: allow
        port: "443"
        proto: tcp

    - name: Habilitar UFW si no está activo
      ufw:
        state: enabled
        policy: allow
