---

- hosts: db_servers
  become: true
  vars:
    ansible_user: loxaservernew
    frontend_port: 8080
    backend_port: 8000  

  tasks:
    - name: Actualizar el sistema
      apt:
        upgrade: dist
        update_cache: yes
      tags: always

    - name: Instalar Podman y herramientas relacionadas
      apt:
        name:
          - podman
          - podman-docker  # Paquete que crea el alias 'docker' -> 'podman'
          - slirp4netns   # Requerido para rootless Podman
        state: present

    - name: Crear alias permanente para docker -> podman (alternativa si podman-docker no funciona)
      blockinfile:
        path: /home/{{ ansible_user }}/.bashrc
        block: |
          alias docker=podman
          alias docker-compose=podman-compose
        marker: "# {mark} ANSIBLE-MANAGED PODMAN ALIAS"

    - name: Instalar UFW (Uncomplicated Firewall)
      apt:
        name: ufw
        state: present
        update_cache: yes

    - name: Permitir puertos necesarios
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - "22"    # SSH
        - "80"    # HTTP
        - "443"   # HTTPS
        - "{{ frontend_port }}"
        - "{{ backend_port }}"

    - name: Habilitar UFW
      ufw:
        state: enabled
        policy: allow