---

- hosts: all
  become: true
  pre_tasks:   

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes

- hosts: web_servers      
  become: true
  tasks:

  - name: install apache2 and php package for Ubuntu
    tags: apache
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: '0644'    
      

- hosts: db_servers 
  become: true
  tasks:

  - name: install mariadb package
    tags: mariadb
    apt:
      name:
        - mariadb-server
      state: latest

